name: Zig Builder
on: [push, workflow_dispatch]
jobs:
  Zig-Latest-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ca-certificates apt-utils
      - name: Copy llvm source list
        run: |
          sudo cp ${{ github.workspace }}/llvm.source.list /etc/apt/sources.list.d/llvm.source.list
      - run: sudo apt-get update -y
      - run: sudo apt-get dist-upgrade -y
      - run: sudo apt install -y build-essential cmake llvm-15 llvm-15-dev lld lld-15 liblld-15-dev clang-15 libclang-15-dev zlib1g-dev git

      - uses: actions/checkout@master
        with:
          repository: ziglang/zig
          path: zig
          ref: master

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/zig

      - name: Make build directory under zig
        run: mkdir ${{ github.workspace }}/zig/build

      - name: Run cmake
        working-directory: ${{ github.workspace }}/zig/build
        run: cmake ..

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
